# Generated by Django 5.1.3 on 2024-12-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("extension", models.CharField(max_length=10)),
                ("is_folder", models.BooleanField()),
                ("size", models.FloatField()),
                ("last_modified", models.DateTimeField()),
                ("created_time", models.DateTimeField()),
                ("is_container", models.BooleanField()),
                ("parent_object", models.CharField(max_length=200)),
                ("within_container", models.BooleanField()),
                ("Office_last_mod_time", models.DateTimeField()),
                ("Office_last_mod_by", models.CharField(max_length=50)),
                ("XLS_num_sheets", models.IntegerField()),
                ("PDF_num_pages", models.IntegerField()),
                ("PDF_layout", models.CharField(max_length=20)),
                ("MP3_track_title", models.CharField(max_length=100)),
                ("MP3_artist", models.CharField(max_length=100)),
                ("MP3_duration", models.CharField(max_length=10)),
                ("AUD_bitrate", models.CharField(max_length=10)),
                ("IMG_size", models.FloatField()),
                ("IMG_dpi", models.CharField(max_length=10)),
                ("IMG_device", models.CharField(max_length=20)),
            ],
        ),
    ]
