# Generated by Django 5.1.3 on 2024-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stknapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="Office_last_mod_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="is_container",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="is_folder",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="parent_object",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="within_container",
            field=models.BooleanField(null=True),
        ),
    ]
