# Generated by Django 5.1.3 on 2024-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stknapp",
            "0003_alter_fileinfo_aud_bitrate_alter_fileinfo_img_device_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="extension",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
